<a href="https://colab.research.google.com/github/AntonioSlip/Engenharia_de_Dados/blob/main/Engenharia_de_Dados_Aula_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Defina uma função que recebe o nome do usuário, e imprime a mensagem na tela: “Olá, xxxx. Seja bem vindo”;

In [ ]:
nome = input("Digite seu nome:")
def boas_vindas(nome):
  print(f"Olá, {nome}, Sejá bem vindo!")
boas_vindas(nome)

Digite seu nome:Antonio
Olá, Antonio, Sejá bem vindo!


Implemente uma função que receba como argumentos dois valores que o usuário informar, e retorne e a soma dos dois valores

In [ ]:


numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
def soma(numero1,numero2):
  print(f"A soma de {numero1} mais {numero2} é igual a {numero1 + numero2}")
soma(numero1,numero2)

Digite o primeiro número:10
Digite o segundo número:20
A soma de 10 mais 20 é igual a 30


Implemente uma função que recebe um número, e retorna se esse número é par ou não.  Use a lista numeros = [ 12, 356, 98,  89, 45, 12, 90, 34, 123, 834, 979 ] para fazer o uso da função

In [ ]:
numeros = [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979]
def pares(numeros):
  for i in numeros:
    if i % 2 == 0:
      print(f"O número {i} é par!")
    else:
      print(f"O número {i} é ímpar!")
pares(numeros)

O número 12 é par!
O número 356 é par!
O número 98 é par!
O número 89 é ímpar!
O número 45 é ímpar!
O número 121 é ímpar!
O número 90 é par!
O número 34 é par!
O número 123 é ímpar!
O número 834 é par!
O número 979 é ímpar!


Faça uma função que receba a altura e o peso de um estudante e calcule e retorne seu IMC

In [ ]:
altura = float(input("Digite sua altura:"))
peso = float(input("Digite seu peso:"))
def calcular_imc(altura,peso):
  imc = peso / altura**2
  print(f"O seu IMC é {round(imc,2)}")
calcular_imc(altura,peso)

Digite sua altura:1.77
Digite seu peso:100
O seu IMC é 31.92


Faça uma função que recebe dois números informados pelo usuário e imprime na tela qual é o maior do dois

In [ ]:
numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
def maior(numero1,numero2):
  if numero1 > numero2:
    print(f"O maior número é {numero1}")  
  elif numero1 < numero2:
    print(f"O maior número é {numero2}") 
  else:
    print("Os números são iguais!")
maior(numero1,numero2)

Digite o primeiro número:30
Digite o segundo número:30
Os números são iguais!


Faça uma função que receba uma lista de números n_lista= [ 12, 356, 98,  89, 45, 12, 90, 34, 123, 834, 979 ] e retorne  a média desses números

In [ ]:
n_lista = [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979]
def media_lista(n_lista):
  soma = 0
  for i in n_lista:
    soma += i
  media = soma /len(n_lista)
  print(f"A média da lista {n_lista} é {round(media,2)}")
media_lista(n_lista)

A média da lista [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979] é 252.82


Faça uma função que receba a lista acima e retorne o menor número

In [ ]:
n_lista = [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979]
def menor_lista(n_lista):
  menor = 999999999999999999999999999
  for i in n_lista:
    if i < menor:
      menor = i
  print(f"O menor número da lista {n_lista} é {menor}")
menor_lista(n_lista)

O menor número da lista [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979] é 12


Faça uma função que use a lista acima e retorne o maior número

In [ ]:
n_lista = [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979]
def maior_lista(n_lista):
  maior = 0
  for i in n_lista:
    if i > maior:
      maior =i
  print(f"O maior número da lista {n_lista} é {maior}")
maior_lista(n_lista)

O maior número da lista [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979] é 979


Crie uma função para deixar um nome somente com as iniciais maiúsculas, independente de como o usuário informar o nome. Receba o nome e use a função para formatá-lo

In [ ]:
nome = input("Digite seu nome completo:")
def iniciais_maiuscula(nome):
  print(f"Seu Nome Com Iniciais Maiúcula: {nome.title()}")
iniciais_maiuscula(nome)

Digite seu nome completo:aNtoNio noBERTo alBUquerQue pereiRa dE liMA
Seu Nome Com Iniciais Maiúcula: Antonio Noberto Albuquerque Pereira De Lima


Faça uma função que recebe uma lista de números e exclui da lista apenas os números pares

In [ ]:
n_lista = [12, 356, 98, 89, 45, 121, 90, 34, 123, 834, 979]
def excluir_pares(n_lista):
  for i in n_lista:
    if i % 2 == 0:
      n_lista.remove(i)
  for i in n_lista:
    if i % 2 == 0:
      n_lista.remove(i)
  print(f"Lista sem os números pares: {n_lista}")
excluir_pares(n_lista)

Lista sem os números pares: [89, 45, 121, 123, 979]


Faça uma função que recebe a média final de um aluno por parâmetro e retorna o seu conceito, conforme a tabela abaixo:


Nota Conceito de 0,0 a 4,9 D
de 5,0 a 6,9 C
de 7,0 a 8,9 B
de 9,0 a 10,0 A



In [ ]:
media_final = float(input("Digite sua média final:"))
def media_conceito(media_final):
  if media_final >= 0.0 and media_final <= 4.9:
    print(f"Conceito: 'D'")
  elif media_final >= 5.0 and media_final <= 6.9:
    print(f"Conceito: 'C'")
  elif media_final >= 7.0 and media_final <= 8.9:
    print(f"Conceito: 'B'")
  elif media_final >= 9.0 and media_final <= 10.0:
    print(f"Conceito: 'A'")
media_conceito(media_final)

Digite sua média final:9.9
Conceito: 'A'


Faça uma função que recebe o diâmetro de uma circunferência e retorna a sua área; Use a expressão A = 2𝝅r², Onde A é a área, 𝝅=3,14, e r é o raio da circunferência, lembrando que r é igual ao diâmetro/2

In [ ]:
diametro = float(input("Digite o diâmetro de uma circunferência:"))
def area_circunferencia(diametro):
  raio =  diametro / 2
  pi = 3.14
  area = 2 * pi * raio**2
  print(f"A area da circunferência é {area}m²")
area_circunferencia(diametro)

Digite o diâmetro de uma circunferência:20
A area da circunferência é 628.0m²


Faça uma função que calcula o valor de uma corrida de Uber. Essa função recebe como argumento a distância a ser percorrida. E calcula da seguinte forma: 5,75 fixo, mais 3,25 por quilômetro. Então solicite a distância da corrida e retorne o valor da corrida, com uma mensagem amigável

In [ ]:
print("Olá usuário! Sejá bem vindo a UBER!")
distancia = float(input("Digite a distância a ser pecorrida:"))
def valor_corrida(distancia):
  valor_fixo = 5.75
  valor_km = 3.25
  valor = valor_fixo + (valor_km * distancia)
  print(f"O valor da corrida de {distancia}km é de R${round(valor,2)}!")
valor_corrida(distancia)

Olá usuário! Sejá bem vindo a UBER!
Digite a distância a ser pecorrida:10.99
O valor da corrida de 10.99km é de R$41.47!


Crie uma função que recebe uma string e  valida o login do usuário, verificar se o nome contém apenas caracteres alfabéticos e possui menos que 30 caracteres, e outra função que recebe uma senha e valida se a senha possui apenas caracteres alfanuméricos. Crie uma função validar_usuario(login, senha) que retorne True se o login e senha forem validados e False se algum não passa na validação. Imprima na tela se o “usuário e senha foram cadastrados com sucesso” ou “Há algum dado inválido”

In [ ]:
login = input("Crie um login:")
senha = input("Crie uma senha:")
def validar_login(login):
  if login.isalpha() == True and len(login) < 30:
    return True
  else:
    return False
def validar_senha(senha):
  if senha.isalnum() == True:
    return True
  else:
    return False
def validar_usuario(login,senha):
  if login == True and senha == True:
    print("Usuário e Senha foram cadastrados com sucesso! \nValidação do usuário:")
    return True
  elif login == False or senha == False:
    print("Há algum dado inválido! \nValidação do usuário:")
    return False
print(f"O login contém apenas caracteres alfabéticos e possui menos que 30 caracteres? {validar_login(login)}")
print(f"A senha possui apenas caracteres alfanuméricos? {validar_senha(senha)}")
print(validar_usuario(validar_login(login),validar_senha(senha)))

Crie um login:aaaaaaaa
Crie uma senha:123@#aa
O login contém apenas caracteres alfabéticos e possui menos que 30 caracteres? True
A senha possui apenas caracteres alfanuméricos? False
Há algum dado inválido! 
Validação do usuário:
False


Vamos fazer uma calculadora simples. Faça uma função chamada operacao_aritmetica( ) que recebe 3 argumentos. Um número, outro número e um sinal aritmético (+, -, / ou *). Então solicite ao usuário os valores de entrada e chame a função operacao_aritmetica( ) , passe seus argumentos e imprima na tela o nome da operação e o resultado. Valide também se o usuário informou um operador inválido, quer dizer diferente de um dos  4 válidos (+, -, / ou *)

In [ ]:
numero1 = float(input("Digite o primeiro número:"))
numero2 = float(input("Digite o segundo número:"))
sinal = input("Escolha a operação aritmética que deseja realizar(+ , - , / ou *):")
def operacao_aritmetica(numero1,numero2,sinal):
  if sinal == "+":
    print(f"Operação Soma: \n{numero1} + {numero2} = {numero1 + numero2}")
  elif sinal == "-":
    print(f"Operação Subtração: \n{numero1} - {numero2} = {numero1 - numero2}")
  elif sinal == "/":
    print(f"Operação Divisão: \n{numero1} / {numero2} = {numero1 / numero2}")
  elif sinal == "*":
    print(f"Operação Multiplicação: \n{numero1} x {numero2} = {numero1 * numero2}")
  else:
    print("Operador Inválido!")
operacao_aritmetica(numero1,numero2,sinal)

Digite o primeiro número:20
Digite o segundo número:10
Escolha a operação aritmética que deseja realizar(+ , - , / ou *):/
Operação Divisão: 
20.0 / 10.0 = 2.0
